
from __future__ import annotations
"""update email model

Revision ID: c056c455979f
Revises: 202402130001
Create Date: 2025-11-15 15:27:40.329388
"""

revision = "c056c455979f"
down_revision = "202402130001"
branch_labels = None
depends_on = None


from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('sender_name', sa.String(length=255), nullable=True))
    op.add_column('emails', sa.Column('sender_email', sa.String(length=255), nullable=True))
    op.add_column('emails', sa.Column('body_preview', sa.Text(), nullable=True))
    op.add_column('emails', sa.Column('body_content', sa.Text(), nullable=True))
    op.add_column('emails', sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('emails', sa.Column('processed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('emails', sa.Column('conversation_id', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('preferences_user_id_key'), 'preferences', type_='unique')
    op.create_unique_constraint('uq_preferences_user_id', 'preferences', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_preferences_user_id', 'preferences', type_='unique')
    op.create_unique_constraint(op.f('preferences_user_id_key'), 'preferences', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('emails', 'conversation_id')
    op.drop_column('emails', 'processed')
    op.drop_column('emails', 'is_read')
    op.drop_column('emails', 'body_content')
    op.drop_column('emails', 'body_preview')
    op.drop_column('emails', 'sender_email')
    op.drop_column('emails', 'sender_name')
    # ### end Alembic commands ###
