from datetime import datetime
from flask_sqlalchemy import SQLAlchemy

# This will be initialized from app.py
db = SQLAlchemy()

class User(db.Model):
    __tablename__ = 'users'
    
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), unique=True, nullable=False)
    name = db.Column(db.String(255), nullable=False)
    microsoft_user_id = db.Column(db.String(255), unique=True, nullable=False)
    refresh_token = db.Column(db.Text, nullable=True)  # Encrypted
    access_token = db.Column(db.Text, nullable=True)   # Encrypted
    token_expires_at = db.Column(db.DateTime, nullable=True)
    
    # User preferences
    tone_profile = db.Column(db.String(50), default='professional')  # professional, friendly, formal
    reply_length = db.Column(db.String(20), default='medium')       # short, medium, long
    auto_reply_enabled = db.Column(db.Boolean, default=False)
    
    # Course/context information
    course_policies = db.Column(db.Text, nullable=True)
    signature = db.Column(db.Text, nullable=True)
    
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    emails = db.relationship("Email", back_populates="user", lazy=True)
    
    def to_dict(self):
        return {
            'id': self.id,
            'email': self.email,
            'name': self.name,
            'tone_profile': self.tone_profile,
            'reply_length': self.reply_length,
            'auto_reply_enabled': self.auto_reply_enabled,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None
        }

class Email(db.Model):
    __tablename__ = 'emails'
    
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    microsoft_message_id = db.Column(db.String(255), unique=True, nullable=False)
    
    # Email content
    subject = db.Column(db.String(500), nullable=False)
    sender_email = db.Column(db.String(255), nullable=False)
    sender_name = db.Column(db.String(255), nullable=True)
    body = db.Column(db.Text, nullable=False)
    body_preview = db.Column(db.String(500), nullable=True)
    
    # Email metadata
    received_at = db.Column(db.DateTime, nullable=False)
    importance = db.Column(db.String(20), default='normal')  # low, normal, high
    is_read = db.Column(db.Boolean, default=False)
    has_attachments = db.Column(db.Boolean, default=False)
    
    # Processing status
    processing_status = db.Column(db.String(50), default='pending')  # pending, processing, processed, failed
    ai_category = db.Column(db.String(100), nullable=True)  # Generated by AI
    priority_level = db.Column(db.Integer, default=3)  # 1-5 scale
    
    # Reply tracking
    requires_reply = db.Column(db.Boolean, default=True)
    reply_generated = db.Column(db.Boolean, default=False)
    reply_sent = db.Column(db.Boolean, default=False)
    reply_sent_at = db.Column(db.DateTime, nullable=True)
    
    # Timestamps
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    processed_at = db.Column(db.DateTime, nullable=True)
    
    # Relationships
    user = db.relationship("User", back_populates="emails")
    replies = db.relationship("EmailReply", back_populates="email", lazy=True)
    
    def to_dict(self):
        return {
            'id': self.id,
            'subject': self.subject,
            'sender_email': self.sender_email,
            'sender_name': self.sender_name,
            'body_preview': self.body_preview,
            'received_at': self.received_at.isoformat() if self.received_at else None,
            'importance': self.importance,
            'is_read': self.is_read,
            'has_attachments': self.has_attachments,
            'processing_status': self.processing_status,
            'ai_category': self.ai_category,
            'priority_level': self.priority_level,
            'requires_reply': self.requires_reply,
            'reply_generated': self.reply_generated,
            'reply_sent': self.reply_sent,
            'reply_sent_at': self.reply_sent_at.isoformat() if self.reply_sent_at else None
        }

class EmailReply(db.Model):
    __tablename__ = 'email_replies'
    
    id = db.Column(db.Integer, primary_key=True)
    email_id = db.Column(db.Integer, db.ForeignKey('emails.id'), nullable=False)
    
    # Reply content
    subject = db.Column(db.String(500), nullable=False)
    body = db.Column(db.Text, nullable=False)
    tone_used = db.Column(db.String(50), nullable=False)
    
    # Generation metadata
    ai_model_version = db.Column(db.String(50), nullable=True)
    generation_prompt = db.Column(db.Text, nullable=True)
    
    # Status tracking
    status = db.Column(db.String(50), default='draft')  # draft, approved, sent, rejected
    is_sent = db.Column(db.Boolean, default=False)
    sent_at = db.Column(db.DateTime, nullable=True)
    
    # User feedback
    user_rating = db.Column(db.Integer, nullable=True)  # 1-5 scale
    user_feedback = db.Column(db.Text, nullable=True)
    
    # Timestamps
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    email = db.relationship("Email", back_populates="replies")
    
    def to_dict(self):
        return {
            'id': self.id,
            'email_id': self.email_id,
            'subject': self.subject,
            'body': self.body,
            'tone_used': self.tone_used,
            'status': self.status,
            'is_sent': self.is_sent,
            'sent_at': self.sent_at.isoformat() if self.sent_at else None,
            'user_rating': self.user_rating,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }

class AIProcessingLog(db.Model):
    __tablename__ = 'ai_processing_logs'
    
    id = db.Column(db.Integer, primary_key=True)
    email_id = db.Column(db.Integer, db.ForeignKey('emails.id'), nullable=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    
    # Processing details
    operation_type = db.Column(db.String(100), nullable=False)  # categorize, generate_reply, etc.
    input_data = db.Column(db.Text, nullable=True)
    output_data = db.Column(db.Text, nullable=True)
    
    # Performance metrics
    processing_time_ms = db.Column(db.Integer, nullable=True)
    token_usage = db.Column(db.Integer, nullable=True)
    model_version = db.Column(db.String(50), nullable=True)
    
    # Status
    status = db.Column(db.String(50), default='completed')  # completed, failed, timeout
    error_message = db.Column(db.Text, nullable=True)
    
    # Timestamps
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    def to_dict(self):
        return {
            'id': self.id,
            'operation_type': self.operation_type,
            'status': self.status,
            'processing_time_ms': self.processing_time_ms,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }

class UserSettings(db.Model):
    __tablename__ = 'user_settings'
    
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    
    # Settings data
    setting_key = db.Column(db.String(100), nullable=False)
    setting_value = db.Column(db.Text, nullable=True)
    setting_type = db.Column(db.String(50), default='string')  # string, json, boolean, integer
    
    # Metadata
    description = db.Column(db.Text, nullable=True)
    is_encrypted = db.Column(db.Boolean, default=False)
    
    # Timestamps
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Unique constraint on user_id + setting_key
    __table_args__ = (db.UniqueConstraint('user_id', 'setting_key', name='unique_user_setting'),)
    
    def to_dict(self):
        return {
            'setting_key': self.setting_key,
            'setting_value': self.setting_value,
            'setting_type': self.setting_type,
            'description': self.description
        }

class LLMMetadata(db.Model):
    __tablename__ = 'llm_metadata'
    
    id = db.Column(db.Integer, primary_key=True)
    email_id = db.Column(db.Integer, db.ForeignKey('emails.id'), nullable=False)
    
    # AI Analysis Results
    category = db.Column(db.String(100), nullable=True)  # student_question, administrative, etc.
    urgency = db.Column(db.String(50), default='normal')  # low, normal, high, critical
    summary = db.Column(db.Text, nullable=True)
    key_points = db.Column(db.Text, nullable=True)  # JSON array of strings
    
    # Risk Assessment
    honor_code_risk = db.Column(db.Boolean, default=False)
    academic_integrity_flags = db.Column(db.Text, nullable=True)  # JSON array
    
    # Processing Metadata
    ai_model_used = db.Column(db.String(100), nullable=True)
    processing_version = db.Column(db.String(50), nullable=True)
    confidence_score = db.Column(db.Float, nullable=True)  # 0.0 to 1.0
    
    # Timestamps
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    def to_dict(self):
        return {
            'id': self.id,
            'email_id': self.email_id,
            'category': self.category,
            'urgency': self.urgency,
            'summary': self.summary,
            'honor_code_risk': self.honor_code_risk,
            'confidence_score': self.confidence_score
        }

class SyncStatus(db.Model):
    __tablename__ = 'sync_status'
    
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    
    # Sync tracking
    last_sync_at = db.Column(db.DateTime, nullable=True)
    last_successful_sync = db.Column(db.DateTime, nullable=True)
    sync_in_progress = db.Column(db.Boolean, default=False)
    
    # Status details
    total_emails_synced = db.Column(db.Integer, default=0)
    last_error = db.Column(db.Text, nullable=True)
    retry_count = db.Column(db.Integer, default=0)
    next_retry_at = db.Column(db.DateTime, nullable=True)
    
    # Timestamps
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    def to_dict(self):
        return {
            'last_sync_at': self.last_sync_at.isoformat() if self.last_sync_at else None,
            'last_successful_sync': self.last_successful_sync.isoformat() if self.last_successful_sync else None,
            'sync_in_progress': self.sync_in_progress,
            'total_emails_synced': self.total_emails_synced
        }

class Embedding(db.Model):
    __tablename__ = 'embeddings'
    
    id = db.Column(db.Integer, primary_key=True)
    email_id = db.Column(db.Integer, db.ForeignKey('emails.id'), nullable=False)
    
    # Embedding data
    embedding_vector = db.Column(db.Text, nullable=False)  # JSON array of floats
    embedding_model = db.Column(db.String(100), nullable=False)
    vector_dimension = db.Column(db.Integer, nullable=False)
    
    # Content metadata
    content_hash = db.Column(db.String(255), nullable=False)  # For deduplication
    content_type = db.Column(db.String(50), default='email_body')  # email_body, subject, etc.
    
    # Timestamps
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    def to_dict(self):
        return {
            'id': self.id,
            'email_id': self.email_id,
            'embedding_model': self.embedding_model,
            'vector_dimension': self.vector_dimension,
            'content_type': self.content_type
        }